export const Brand = [
  { key: "1", value: "Acura" },
  { key: "2", value: "Alfa Romeo" },
  { key: "3", value: "Aston Martin" },
  { key: "4", value: "Audi" },
  { key: "5", value: "Bentley" },
  { key: "6", value: "BMW" },
  { key: "7", value: "Buick" },
  { key: "8", value: "Cadillac" },
  { key: "9", value: "Chevrolet" },
  { key: "10", value: "Chrysler" },
  { key: "11", value: "Dodge" },
  { key: "12", value: "Ferrari" },
  { key: "13", value: "Fiat" },
  { key: "14", value: "Ford" },
  { key: "15", value: "Genesis" },
  { key: "16", value: "GMC" },
  { key: "17", value: "Honda" },
  { key: "18", value: "Hyundai" },
  { key: "19", value: "Infiniti" },
  { key: "20", value: "Jaguar" },
  { key: "21", value: "Jeep" },
  { key: "22", value: "Kia" },
  { key: "23", value: "Lamborghini" },
  { key: "24", value: "Land Rover" },
  { key: "25", value: "Lexus" },
  { key: "26", value: "Lincoln" },
  { key: "27", value: "Lotus" },
  { key: "28", value: "Maserati" },
  { key: "29", value: "Mazda" },
  { key: "30", value: "McLaren" },
  { key: "31", value: "Mercedes-Benz" },
  { key: "32", value: "Mini" },
  { key: "33", value: "Mitsubishi" },
  { key: "34", value: "Nissan" },
  { key: "35", value: "Polestar" },
  { key: "36", value: "Porsche" },
  { key: "37", value: "Ram" },
  { key: "38", value: "Rivian" },
  { key: "39", value: "Rolls-Royce" },
  { key: "40", value: "Subaru" },
  { key: "41", value: "Tesla" },
  { key: "42", value: "Toyota" },
  { key: "43", value: "Volkswagen" },
  { key: "44", value: "Volvo" },
];

export const FuelType = [
  { key: "1", value: "CNG & Hybrids" },
  { key: "2", value: "Diesel" },
  { key: "3", value: "Electric" },
  { key: "4", value: "LPG" },
  { key: "5", value: "Petrol" },
];

export const Trans = [
  { key: "1", value: "Automatic" },
  { key: "2", value: "Manual" },
];

export const NumberOfOwnerd = [
  { key: "1", value: "1" },
  { key: "2", value: "2" },
  { key: "3", value: "3" },
  { key: "4", value: "4" },
  { key: "5", value: "4+" },
];

export const MobileBarnd = [
  { key: "1", value: "Samsung" },
  { key: "2", value: "Apple" },
  { key: "3", value: "Huawei" },
  { key: "4", value: "Xiaomi" },
  { key: "5", value: "Oppo" },
  { key: "6", value: "Vivo" },
  { key: "7", value: "OnePlus" },
  { key: "8", value: "Google" },
  { key: "9", value: "Motorola" },
  { key: "10", value: "Sony" },
  { key: "11", value: "LG" },
  { key: "12", value: "Nokia" },
  { key: "13", value: "HTC" },
  { key: "14", value: "Lenovo" },
  { key: "15", value: "ASUS" },
  { key: "16", value: "BlackBerry" },
  { key: "17", value: "ZTE" },
  { key: "18", value: "Alcatel" },
  { key: "19", value: "TCL" },
  { key: "20", value: "Realme" },
];

export const bikes = [
  { key: "1", value: "Honda" },
  { key: "2", value: "Yamaha" },
  { key: "3", value: "Suzuki" },
  { key: "4", value: "Kawasaki" },
  { key: "5", value: "Ducati" },
  { key: "6", value: "BMW Motorrad" },
  { key: "7", value: "Harley-Davidson" },
  { key: "8", value: "Triumph" },
  { key: "9", value: "KTM" },
  { key: "10", value: "Royal Enfield" },
  { key: "11", value: "Aprilia" },
  { key: "12", value: "Moto Guzzi" },
  { key: "13", value: "Bajaj" },
  { key: "14", value: "MV Agusta" },
  { key: "15", value: "Hero" },
  { key: "16", value: "Indian Motorcycle" },
  { key: "17", value: "Benelli" },
  { key: "18", value: "Husqvarna" },
  { key: "19", value: "TVS" },
  { key: "20", value: "Zero Motorcycles" },
];

export const Electronics = [
  { key: "1", value: "TVs, Video - Audio" },
  { key: "2", value: "Kitchen & Other Appliances" },
  { key: "3", value: "Computers & Laptops" },
  { key: "4", value: "Cameras & Lenses" },
  { key: "5", value: "Games & Entertainment" },
  { key: "6", value: "Fridges" },
  { key: "7", value: "Computer Accessories" },
  { key: "8", value: "Hard Disks, Printers & Monitors" },
  { key: "9", value: "ACs" },
  { key: "10", value: "Washing Machines" },
  { key: "11", value: "other" },
];

export const Used = [
  { key: "1", value: "New" },
  { key: "2", value: "Old" },
];

export const Bicycles = [
  { key: "1", value: "Hercules" },
  { key: "2", value: "Hero" },
  { key: "3", value: "Other Brands add this data in api" },
];

export const Access = [
  { key: "1", value: "Mobile" },
  { key: "2", value: "Tablet" },
];

export const Fashions = [
  { key: "1", value: "Men" },
  { key: "2", value: "Women" },
  { key: "3", value: "Kids" },
  { key: "3", value: "Kids" },
  { key: "4", value: "other" },
];

export const MotherTongue = [
  { key: "2", value: "Assamese" },
  { key: "3", value: "Bengali" },
  { key: "4", value: "English" },
  { key: "5", value: "Gujarati" },
  { key: "6", value: "Hindi" },
  { key: "7", value: "Kannada" },
  { key: "8", value: "Konkani" },
  { key: "9", value: "Malayalam" },
  { key: "10", value: "Marathi" },
  { key: "11", value: "Marwari" },
  { key: "11", value: "Odia" },
  { key: "12", value: "Punjabi" },
  { key: "13", value: "Sindhi" },
  { key: "14", value: "Tamil" },
  { key: "15", value: "Telugu" },
  { key: "16", value: "Urdu" },
  { key: "17", value: "Aka" },
  { key: "18", value: "Arabic" },
  { key: "19", value: "Arunachali" },
  { key: "20", value: "Awadhi" },
  { key: "21", value: "Baluchi" },
  { key: "22", value: "Bhojpuri" },
  { key: "23", value: "Bhutia" },
  { key: "24", value: "Brahui" },
  { key: "25", value: "Brij" },
  { key: "26", value: "Burmese" },
  { key: "27", value: "Chattisgarhi" },
  { key: "28", value: "Chinese" },
  { key: "29", value: "Coorgi" },
  { key: "30", value: "Dogi" },
  { key: "31", value: "French" },
  { key: "32", value: "Garhwali" },
  { key: "33", value: "Garo" },
  { key: "34", value: "Haryanavi" },
  { key: "35", value: "Himachali/Pahari" },
  { key: "36", value: "Hindko" },
  { key: "37", value: "Kakbarak" },
  { key: "38", value: "Kanauji" },
  { key: "39", value: "Kashmiri" },
  { key: "40", value: "Khandesi" },
  { key: "41", value: "Khasi" },
  { key: "42", value: "Koshali" },
  { key: "43", value: "Kumaoni" },
  { key: "44", value: "Kutchi" },
  { key: "45", value: "Ladakhi" },
  { key: "46", value: "Lepcha" },
  { key: "47", value: "Magahi" },
  { key: "48", value: "Maithili" },
  { key: "49", value: "Malay" },
  { key: "50", value: "Manipuri" },
  { key: "51", value: "Miji" },
  { key: "52", value: "Mizo" },
  { key: "53", value: "Monpa" },
  { key: "54", value: "Nepali" },
  { key: "55", value: "Pashto" },
  { key: "56", value: "Persian" },
  { key: "57", value: "Rajasthani" },
  { key: "58", value: "Russian" },
  { key: "59", value: "Santhali" },
  { key: "60", value: "Seraiki" },
  { key: "61", value: "Sinhala" },
  { key: "62", value: "Sourashtra" },
  { key: "63", value: "Spanish" },
  { key: "64", value: "Swedish" },
  { key: "65", value: "Tagalog" },
  { key: "66", value: "Tulu" },
  { key: "67", value: "Other" },
];

export const FurnitureType = [
  { key: "1", value: "Sofa & Dining" },
  { key: "2", value: "Beds & Wardrobes" },
  { key: "3", value: "Home Decor & Garden" },
  { key: "4", value: "Kids Furniture" },
  { key: "5", value: "Other Household Items" },
  { key: "6", value: "Other" },
];
