export const Annualincome = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Specify an Inco" },
  ];
  
  export const Marital = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Never Married" },
    { key: "3", value: "Divorced" },
    { key: "4", value: "Widowed" },
    { key: "5", value: "Awaiting Divorce" },
    { key: "6", value: "Diary Products" },
    { key: "7", value: "Annulled" },
    { key: "8", value: "Single" },
  ];
  
  export const Religion = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Hindu" },
    { key: "3", value: "Muslim" },
    { key: "4", value: "Christian" },
    { key: "5", value: "Sikh" },
    { key: "6", value: "Parsi" },
    { key: "7", value: "Jain" },
    { key: "8", value: "Buddhist" },
    { key: "9", value: "Jewish" },
    { key: "10", value: "No Religion" },
    { key: "11", value: "Spritual - not religious" },
    { key: "11", value: "Other" },
  ];
  
  export const Community = [
    { key: "1", value: "Digambar" },
    { key: "2", value: "Shetamber" },
    { key: "3", value: "Vania" },
    { key: "4", value: "Porwal" },
  ];
  
  export const Qualification = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Doctorate" },
    { key: "7", value: "Masters" },
    { key: "3", value: "Master" },
    { key: "4", value: "Bachelor / UnderGraduate" },
    { key: "5", value: "Associate / Diploma" },
    { key: "6", value: "High School and Below" },
  ];
  
  export const Diet = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Veg" },
    { key: "3", value: "Jain" },
    { key: "4", value: "Vegan" },
    { key: "5", value: "Non-veg" },
    { key: "6", value: "Other" },
  ];
  
  export const WorkingWith = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Private Company" },
    { key: "3", value: "Government / Public Sector" },
    { key: "4", value: "Defense / Civil Services" },
    { key: "5", value: "Business / Self Employed" },
    { key: "6", value: "Not Working" },
  ];
  
  export const Mangglik = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Only Mangliks" },
    { key: "3", value: "No Mangliks" },
  ];
  
  export const Country = [
    { key: "1", value: "Doesn't Matter" },
    { key: "13", value: "Country" },
    { key: "2", value: "India" },
    { key: "3", value: "USA" },
    { key: "4", value: "Uk" },
    { key: "5", value: "UAE" },
    { key: "6", value: "Canada" },
    { key: "7", value: "Australia" },
    { key: "8", value: "New Zealand" },
    { key: "9", value: "Pakistan" },
    { key: "10", value: "Saudi Arabia" },
    { key: "11", value: "Kuwait" },
    { key: "12", value: "South Africa" },
  ];
  
  export const Countrys = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "India" },
    { key: "3", value: "USA" },
    { key: "4", value: "Uk" },
    { key: "5", value: "UAE" },
    { key: "6", value: "Canada" },
    { key: "7", value: "Australia" },
    { key: "8", value: "New Zealand" },
    { key: "9", value: "Pakistan" },
    { key: "10", value: "Saudi Arabia" },
    { key: "11", value: "Kuwait" },
    { key: "11", value: "South Africa" },
  ];
  
  export const EducationArea = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Engineering" },
    { key: "3", value: "Arts / Desing" },
    { key: "4", value: "Finance / Commerce" },
    { key: "5", value: "Computers / IT" },
    { key: "6", value: "Science" },
    { key: "7", value: "Medicine" },
    { key: "8", value: "Managemant" },
    { key: "9", value: "Law" },
  ];
  
  export const Profilecreate = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Self" },
    { key: "3", value: "Parent / Guardian" },
    { key: "4", value: "Sibling / Fiend / Other" },
  ];
  
  export const Residency = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Work/Student Visa" },
    { key: "3", value: "Citizen/Permanent Resident" },
  ];
  
  export const Photo = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Visible to all" },
    { key: "3", value: "Protected Photo" },
  ];
  
  export const MotherTongue = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Assamese" },
    { key: "3", value: "Bengali" },
    { key: "4", value: "English" },
    { key: "5", value: "Gujarati" },
    { key: "6", value: "Hindi" },
    { key: "7", value: "Kannada" },
    { key: "8", value: "Konkani" },
    { key: "9", value: "Malayalam" },
    { key: "10", value: "Marathi" },
    { key: "11", value: "Marwari" },
    { key: "11", value: "Odia" },
    { key: "12", value: "Punjabi" },
    { key: "13", value: "Sindhi" },
    { key: "14", value: "Tamil" },
    { key: "15", value: "Telugu" },
    { key: "16", value: "Urdu" },
    { key: "17", value: "Aka" },
    { key: "18", value: "Arabic" },
    { key: "19", value: "Arunachali" },
    { key: "20", value: "Awadhi" },
    { key: "21", value: "Baluchi" },
    { key: "22", value: "Bhojpuri" },
    { key: "23", value: "Bhutia" },
    { key: "24", value: "Brahui" },
    { key: "25", value: "Brij" },
    { key: "26", value: "Burmese" },
    { key: "27", value: "Chattisgarhi" },
    { key: "28", value: "Chinese" },
    { key: "29", value: "Coorgi" },
    { key: "30", value: "Dogi" },
    { key: "31", value: "French" },
    { key: "32", value: "Garhwali" },
    { key: "33", value: "Garo" },
    { key: "34", value: "Haryanavi" },
    { key: "35", value: "Himachali/Pahari" },
    { key: "36", value: "Hindko" },
    { key: "37", value: "Kakbarak" },
    { key: "38", value: "Kanauji" },
    { key: "39", value: "Kashmiri" },
    { key: "40", value: "Khandesi" },
    { key: "41", value: "Khasi" },
    { key: "42", value: "Koshali" },
    { key: "43", value: "Kumaoni" },
    { key: "44", value: "Kutchi" },
    { key: "45", value: "Ladakhi" },
    { key: "46", value: "Lepcha" },
    { key: "47", value: "Magahi" },
    { key: "48", value: "Maithili" },
    { key: "49", value: "Malay" },
    { key: "50", value: "Manipuri" },
    { key: "51", value: "Miji" },
    { key: "52", value: "Mizo" },
    { key: "53", value: "Monpa" },
    { key: "54", value: "Nepali" },
    { key: "55", value: "Pashto" },
    { key: "56", value: "Persian" },
    { key: "57", value: "Rajasthani" },
    { key: "58", value: "Russian" },
    { key: "59", value: "Santhali" },
    { key: "60", value: "Seraiki" },
    { key: "61", value: "Sinhala" },
    { key: "62", value: "Sourashtra" },
    { key: "63", value: "Spanish" },
    { key: "64", value: "Swedish" },
    { key: "65", value: "Tagalog" },
    { key: "66", value: "Tulu" },
    { key: "67", value: "Other" },
  ];
  export const Stateliving = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Andaman & Nicobar" },
    { key: "3", value: "Andhra Pradesh" },
    { key: "4", value: "Arunachal Pradesh" },
    { key: "5", value: "Assam" },
    { key: "6", value: "Bihar" },
    { key: "7", value: "Chandigarh" },
    { key: "8", value: "Chhattisgarh" },
    { key: "9", value: "Dadra & Nagar Haveli" },
    { key: "10", value: "Daman & Diu" },
    { key: "11", value: "Delhi-NCR" },
    { key: "12", value: "Goa" },
    { key: "13", value: "Gujarati" },
    { key: "14", value: "Haryana" },
    { key: "15", value: "Himachal Pradesh" },
    { key: "16", value: "Jammu & Kashmir" },
    { key: "17", value: "JharKhand" },
    { key: "18", value: "Karnataka" },
    { key: "19", value: "Kerala" },
    { key: "20", value: "Lakshadweep" },
    { key: "21", value: "Madhya Pradesh" },
    { key: "22", value: "Maharashtra" },
    { key: "23", value: "Manipur" },
    { key: "24", value: "Meghalaya" },
    { key: "25", value: "Mizoram" },
    { key: "26", value: "Nagaland" },
    { key: "27", value: "Orissa" },
    { key: "28", value: "Pondicherry" },
    { key: "29", value: "Punjab" },
    { key: "30", value: "Rajashan" },
    { key: "31", value: "Sikkim" },
    { key: "32", value: "Tamil Nadu" },
    { key: "33", value: "Telangana" },
    { key: "34", value: "Tripura" },
    { key: "35", value: "Uttar Pradesh" },
    { key: "36", value: "Uttaranchal" },
    { key: "37", value: "West Bengal" },
  ];
  
  export const ProfessionArea = [
    { key: "1", value: "Doesn't Matter" },
    { key: "2", value: "Accounting, Banking & Finace" },
    { key: "3", value: "Administration & HR" },
    { key: "4", value: "Advertising, Media & Entertainment" },
    { key: "5", value: "Agriculture" },
    { key: "6", value: "Airline & Aviation" },
    { key: "7", value: "Architecture & Desing" },
    { key: "8", value: "Artists, Animators & Web Designers" },
    { key: "9", value: "BPO,KPO, & Customer Support" },
    { key: "10", value: "Beauty,Fashion & Jewellery Desiners" },
    { key: "11", value: "Civil Services/Law Enforcement" },
    { key: "12", value: "Corporate Professionals" },
    { key: "13", value: "Defense" },
    { key: "14", value: "Education & Training" },
    { key: "15", value: "Engineering" },
    { key: "16", value: "Hotel & Hospitality" },
    { key: "17", value: "IT & Software Engineering" },
    { key: "18", value: "Legal" },
    { key: "19", value: "Medical & Healthcare" },
    { key: "20", value: "Merchant Navy" },
    { key: "21", value: "Non Working" },
    { key: "22", value: "Others" },
    { key: "23", value: "Sales & Marketing" },
    { key: "24", value: "Science" },
  ];
  